### ISSUE TITLE
ValueError: [E030] Sentence boundaries unset. You can add the 'sentencizer' component to the pipeline with: nlp.add_pipe(nlp.create_pipe('sentencizer')) Alternatively, add the dependency parser, or set sentence boundaries by setting doc[i].is_sent_start.

### ISSUE THREAD

**Issue by yangchangli** [luisfredgs/cnn-hierarchical-network-for-document-classification#1]
Hello, I have the following error when I run your file. I hope you can help me answer it.
my spacy version is   2.1.3

There is an error in this position：datase.py
for sentence in tqdm(doc.sents):

ERROR：
ValueError: [E030] Sentence boundaries unset. You can add the 'sentencizer' component to the pipeline with: nlp.add_pipe(nlp.create_pipe('sentencizer')) Alternatively, add the dependency parser, or set sentence boundaries by setting doc[i].is_sent_start.

**Comment by yangchangli** [comment]
spacy version issue

version 2.1.0 is worded

**Comment by luisfredgs** [comment]
Hello! This code was tested with spacy 2.0.x.

**Comment by yangchangli** [comment]
Thank you very much for your prompt reply, both 2.1.x and 2.0.x are OK.
thank you
