### ISSUE TITLE
I can't download A and B. Can you send me a copy?thank you very much

### ISSUE THREAD

**Issue by yangchangli** [luisfredgs/cnn-hierarchical-network-for-document-classification#2]
I can't download "kaggle datasets download -d luisfredgs/in1164-deep-learning" and "kaggle datasets download -d luisfredgs/wiki-news-300d-1m-subword". Can you send me a copy?
thank you very much
yang2012naf@163.com

**Comment by luisfredgs** [comment]
For download datasets,  check the documentation for kaggle api: https://github.com/Kaggle/kaggle-api or https://www.kaggle.com/luisfredgs/in1164-deep-learning and https://www.kaggle.com/luisfredgs/wiki-news-300d-1m-subword

**Comment by yangchangli** [comment]
Thank you very much for your timely reply. it is very important for me .

At 2019-04-12 09:48:26, "Luís Fred" <notifications@github.com> wrote:


For download datasets, check the documentation for kaggle api: https://github.com/Kaggle/kaggle-api or https://www.kaggle.com/luisfredgs/in1164-deep-learning
